Logging to ./qwen_triton_sft/logs
Logging into HF

    _|    _|  _|    _|    _|_|_|    _|_|_|  _|_|_|  _|      _|    _|_|_|      _|_|_|_|    _|_|      _|_|_|  _|_|_|_|
    _|    _|  _|    _|  _|        _|          _|    _|_|    _|  _|            _|        _|    _|  _|        _|
    _|_|_|_|  _|    _|  _|  _|_|  _|  _|_|    _|    _|  _|  _|  _|  _|_|      _|_|_|    _|_|_|_|  _|        _|_|_|
    _|    _|  _|    _|  _|    _|  _|    _|    _|    _|    _|_|  _|    _|      _|        _|    _|  _|        _|
    _|    _|    _|_|      _|_|_|    _|_|_|  _|_|_|  _|      _|    _|_|_|      _|        _|    _|    _|_|_|  _|_|_|_|

[1m[31mCannot authenticate through git-credential as no helper is defined on your machine.
You might have to re-authenticate when pushing to the Hugging Face Hub.
Run the following command in your terminal in case you want to set the 'store' credential helper as default.

git config --global credential.helper store

Read https://git-scm.com/book/en/v2/Git-Tools-Credential-Storage for more details.[0m
Token has not been saved to git credential helper.
Loading dataset from cdreetz/triton-sft-dataset...
Loaded 989 examples
Train: 890, Eval: 99
Epoch 1:   0%|â–Ž                                                                                                                                                          | 1/445 [00:05<38:25,  5.19s/it]
Traceback (most recent call last):
  File "/home/ubuntu/rlptx/sft_grpo/trainer.py", line 407, in <module>
    model = trainer_setup.train(
  File "/home/ubuntu/rlptx/sft_grpo/trainer.py", line 300, in train
    train_loss = self.train_epoch(
  File "/home/ubuntu/rlptx/sft_grpo/trainer.py", line 177, in train_epoch
    self.global_step += 1
AttributeError: 'SFTTrainingSetup' object has no attribute 'global_step'
